#!/bin/bash
SCRIPT="$(readlink -f "$0")"
DIR="$(dirname "$SCRIPT")"
cd "$DIR" || exit 1
export LD_LIBRARY_PATH="$DIR/../qawno:$LD_LIBRARY_PATH"
exec "$DIR/../qawno/pawncc" main.pwn -omain.amx \
    -i"$DIR/../qawno/include" \
    "$@"
